import { useState, useEffect, type FormEvent } from "react";
import { User as UserIcon, Loader2, AlertCircle, Pencil, AlertTriangle, Lock } from "lucide-react";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogFooter } from "../ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../ui/select";
import { Label } from "../ui/label";
import { useTranslation } from "react-i18next";
import { THEME } from "../../constants/projectConstants"; 
import { api } from "../../services/api";

// Interfaces
interface AddUserModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSubmitAction: (payload: any) => Promise<void>;
}

interface EditUserModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  userData: any;
  onSubmitAction: (id: string, payload: any) => Promise<void>;
}

interface ConfirmActionModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  title: string;
  description: string;
  actionLabel: string;
  variant?: "danger" | "primary";
  onConfirm: () => Promise<void>;
}

const inputClass = `h-10 bg-gray-50/50 border-gray-200 focus-visible:bg-white focus-visible:ring-0 focus-visible:ring-offset-0 focus-visible:border-[${THEME.TOSCA}] transition-all duration-300`;

// 1. ADD USER MODAL (PASSWORD GENERATED BY SYSTEM)
const INITIAL_FORM = { name: "", email: "", role: "OFFICER" };

export function AddUserModal({ open, onOpenChange, onSubmitAction }: AddUserModalProps) {
  const { t } = useTranslation();
  
  const [form, setForm] = useState(INITIAL_FORM);
  const [ui, setUi] = useState({ loading: false, error: "" });

  useEffect(() => {
    if (!open) {
      setForm(INITIAL_FORM);
      setUi({ loading: false, error: "" });
    }
  }, [open]);

  const updateForm = (e: React.ChangeEvent<HTMLInputElement>) => {
    setForm({ ...form, [e.target.id]: e.target.value });
    if (ui.error) setUi(prev => ({ ...prev, error: "" }));
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setUi({ loading: true, error: "" });

    try {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(form.email)) {
        throw new Error(t('admin.userManagement.modal.errorInvalidEmail', 'Format email tidak valid!'));
      }

      // Validasi email ke backend
      try {
        await api.post("/auth/validate-email", { email: form.email });
      } catch (apiErr: any) {
        throw new Error(apiErr.response?.data?.message || t('admin.userManagement.modal.errorEmailTaken', 'Email sudah terdaftar atau tidak valid'));
      }

      // 🔥 Payload dikirim tanpa password statis. 
      // Backend akan men-generate random password dan mengirimnya ke email user.
      await onSubmitAction(form);
      onOpenChange(false);
      
    } catch (err: any) {
      setUi({ loading: false, error: err.message || t('admin.userManagement.modal.errorDefault', 'Terjadi kesalahan') });
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px] bg-white p-0 border-none shadow-2xl rounded-3xl overflow-hidden">
        <div className="bg-gray-50/80 border-b border-gray-100 p-6">
          <DialogTitle className="text-xl font-bold text-gray-900 flex items-center gap-2">
            <UserIcon style={{ color: THEME.TOSCA }} className="h-5 w-5" /> {t('admin.userManagement.modal.title', 'Buat Akun Baru')}
          </DialogTitle>
          <DialogDescription className="mt-1">
            {t('admin.userManagement.modal.desc', 'Buat kredensial untuk anggota tim baru.')}
          </DialogDescription>
        </div>
        
        <form onSubmit={handleSubmit} className="p-6 space-y-5">
          {ui.error && (
            <div className="p-3 bg-red-50 text-red-600 text-xs font-bold rounded-xl flex items-center gap-2 animate-in fade-in slide-in-from-top-1">
              <AlertCircle className="h-4 w-4 shrink-0" /> 
              <span>{ui.error}</span>
            </div>
          )}

          <div className="space-y-2">
            <Label className="text-gray-700 font-semibold">{t('admin.userManagement.modal.nameLabel', 'Nama Lengkap')}</Label>
            <Input id="name" placeholder="Masukkan nama lengkap..." required value={form.name} onChange={updateForm} className={inputClass} disabled={ui.loading} />
          </div>
          
          <div className="space-y-2">
            <Label className="text-gray-700 font-semibold">{t('admin.userManagement.modal.emailLabel', 'Email Kerja')}</Label>
            <Input id="email" type="email" placeholder="nama@bsi.co.id" required value={form.email} onChange={updateForm} className={inputClass} disabled={ui.loading} />
          </div>

          <div className="space-y-2">
            <Label className="text-gray-700 font-semibold">{t('admin.userManagement.modal.roleLabel', 'Role Akses')}</Label>
            <Select value={form.role} onValueChange={(v) => setForm({...form, role: v})} disabled={ui.loading}>
              <SelectTrigger className="h-10 bg-gray-50/50 border-gray-200 focus:ring-0 rounded-xl font-medium">
                <SelectValue />
              </SelectTrigger>
              <SelectContent className="bg-white rounded-xl shadow-xl">
                <SelectItem value="HEAD" className="font-medium cursor-pointer">HEAD</SelectItem>
                <SelectItem value="OFFICER" className="font-medium cursor-pointer">OFFICER</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="p-4 bg-blue-50 border border-blue-100 rounded-2xl flex items-start gap-3">
            <div className="h-8 w-8 rounded-full bg-blue-100 flex items-center justify-center shrink-0">
                <AlertTriangle className="h-4 w-4 text-blue-600" />
            </div>
            <div className="text-xs text-blue-800 leading-relaxed">
              <span className="font-bold block text-sm mb-0.5">{t('admin.userManagement.modal.securityInfo', 'Info Keamanan')}</span> 
              Sistem akan membuatkan <span className="font-bold">Password Acak</span> yang aman secara otomatis. Kredensial login akan dikirimkan langsung ke <span className="font-bold italic">Email Kerja</span> yang didaftarkan di atas.
            </div>
          </div>

          <DialogFooter className="pt-4 mt-2 border-t border-gray-50">
            <Button type="button" variant="ghost" onClick={() => onOpenChange(false)} disabled={ui.loading} className="rounded-xl font-bold">
              {t('admin.userManagement.modal.cancel', 'Batal')}
            </Button>
            <Button type="submit" disabled={ui.loading} style={{ backgroundColor: THEME.TOSCA }} className="text-white hover:brightness-95 rounded-xl px-8 shadow-md transition-all font-bold">
              {ui.loading ? <><Loader2 className="mr-2 h-4 w-4 animate-spin"/> {t('admin.userManagement.modal.saving', 'Processing...')}</> : t('admin.userManagement.modal.save', 'Simpan Akun')}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

// 2. EDIT USER MODAL (NAME & EMAIL LOCKED)
export function EditUserModal({ open, onOpenChange, userData, onSubmitAction }: EditUserModalProps) {
  const { t } = useTranslation();
  const [ui, setUi] = useState({ loading: false, error: "" });
  const [form, setForm] = useState({ name: "", email: "", role: "OFFICER" });

  useEffect(() => {
    if (userData && open) {
      setForm({
        name: userData.name || "",
        email: userData.email || "",
        role: userData.role === "ADMIN" ? "OFFICER" : (userData.role || "OFFICER")
      });
      setUi({ loading: false, error: "" });
    }
  }, [userData, open]);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setUi({ loading: true, error: "" });
    
    try {
      // 🔥 Sesuai permintaan: Hanya mengirim 'role' karena Name & Email tidak boleh diubah Admin
      await onSubmitAction(userData.id, { role: form.role });
      onOpenChange(false);
    } catch (err: any) {
      setUi({ loading: false, error: err.message || t('admin.userManagement.modal.errorDefault', 'Terjadi kesalahan') });
    }
  };

  if (!userData) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px] bg-white p-0 border-none shadow-2xl rounded-3xl overflow-hidden">
        <div className="bg-gray-50/80 border-b border-gray-100 p-6">
          <DialogTitle className="text-xl font-bold text-gray-900 flex items-center gap-2">
            <Pencil style={{ color: THEME.TOSCA }} className="h-5 w-5" /> {t('admin.userManagement.modal.editTitle', 'Edit Profil Pengguna')}
          </DialogTitle>
          <DialogDescription className="mt-1">
            {t('admin.userManagement.modal.editDesc', 'Ubah hak akses pengguna ini.')}
          </DialogDescription>
        </div>
        
        <form onSubmit={handleSubmit} className="p-6 space-y-5">
          {ui.error && (
            <div className="p-3 bg-red-50 text-red-600 text-xs font-bold rounded-xl flex items-center gap-2 animate-in fade-in slide-in-from-top-1">
              <AlertCircle className="h-4 w-4 shrink-0" /> 
              <span>{ui.error}</span>
            </div>
          )}
          
          <div className="space-y-2 opacity-70 group">
            <Label className="text-gray-500 font-semibold flex items-center gap-2">
               <Lock className="h-3 w-3" /> {t('admin.userManagement.modal.nameLabel', 'Nama Lengkap')}
            </Label>
            <Input 
                value={form.name} 
                disabled 
                className={`${inputClass} cursor-not-allowed bg-gray-100/50 border-gray-100 font-medium`} 
            />
            <p className="text-[10px] text-gray-400 italic px-1">Nama lengkap hanya dapat diubah oleh pemilik akun.</p>
          </div>
          
          <div className="space-y-2 opacity-70">
            <Label className="text-gray-500 font-semibold flex items-center gap-2">
                <Lock className="h-3 w-3" /> {t('admin.userManagement.modal.emailLabel', 'Email Kerja')}
            </Label>
            <Input 
                type="email" 
                value={form.email} 
                disabled 
                className={`${inputClass} cursor-not-allowed bg-gray-100/50 border-gray-100 font-medium`} 
            />
            <p className="text-[10px] text-gray-400 italic px-1">Alamat email terikat pada identitas sistem.</p>
          </div>
          
          <div className="space-y-2">
            <Label className="text-gray-700 font-bold">{t('admin.userManagement.modal.roleLabel', 'Role Akses')}</Label>
            <Select value={form.role} onValueChange={v => setForm({...form, role: v})} disabled={ui.loading}>
              <SelectTrigger className="h-10 bg-gray-50/50 border-gray-200 focus:ring-0 rounded-xl font-bold text-[#38A79C]">
                <SelectValue />
              </SelectTrigger>
              <SelectContent className="bg-white rounded-xl shadow-xl">
                <SelectItem value="HEAD" className="font-bold cursor-pointer">HEAD</SelectItem>
                <SelectItem value="OFFICER" className="font-bold cursor-pointer">OFFICER</SelectItem>
              </SelectContent>
            </Select>
          </div>
          
          <DialogFooter className="pt-4 mt-2 border-t border-gray-50">
            <Button type="button" variant="ghost" onClick={() => onOpenChange(false)} disabled={ui.loading} className="rounded-xl font-bold">
              {t('admin.userManagement.modal.cancel', 'Batal')}
            </Button>
            <Button type="submit" disabled={ui.loading} style={{ backgroundColor: THEME.TOSCA }} className="text-white hover:brightness-95 rounded-xl px-8 shadow-md transition-all font-bold">
              {ui.loading ? <><Loader2 className="mr-2 h-4 w-4 animate-spin"/> {t('admin.userManagement.modal.saving', 'Processing...')}</> : t('admin.userManagement.modal.saveChanges', 'Simpan Perubahan')}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

// 3. CONFIRM ACTION MODAL
export function ConfirmActionModal({ open, onOpenChange, title, description, actionLabel, variant = "danger", onConfirm }: ConfirmActionModalProps) {
  const { t } = useTranslation();
  const [isLoading, setIsLoading] = useState(false);

  const handleConfirm = async () => {
    setIsLoading(true);
    try { 
      await onConfirm(); 
      onOpenChange(false); 
    } catch (error) { 
      console.error(error); 
    } finally { 
      setIsLoading(false); 
    }
  };

  const isDanger = variant === "danger";

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[400px] bg-white p-6 border-none shadow-2xl rounded-3xl animate-in zoom-in-95 duration-200">
        <div className="flex flex-col items-center text-center space-y-4">
          <div 
            className={`h-16 w-16 rounded-full flex items-center justify-center ${isDanger ? 'bg-red-50' : 'bg-blue-50'}`}
            style={!isDanger && !variant ? { backgroundColor: `${THEME.TOSCA}1A` } : {}}
          >
            {isDanger ? (
                <AlertTriangle className="h-8 w-8 text-red-600" />
            ) : (
                <UserIcon className="h-8 w-8 text-blue-600" />
            )}
          </div>
          <div>
            <DialogTitle className="text-xl font-bold text-gray-900">{title}</DialogTitle>
            <DialogDescription className="text-sm text-gray-500 mt-2 leading-relaxed">{description}</DialogDescription>
          </div>
        </div>
        
        <DialogFooter className="flex gap-2 w-full sm:justify-center mt-6">
          <Button variant="ghost" onClick={() => onOpenChange(false)} className="flex-1 rounded-xl font-bold" disabled={isLoading}>
            {t('admin.userManagement.modal.cancel', 'Batal')}
          </Button>
          <Button 
            onClick={handleConfirm} 
            disabled={isLoading} 
            className={`flex-1 rounded-xl shadow-md transition-all font-bold ${isDanger ? 'bg-red-600 hover:bg-red-700 text-white' : 'bg-blue-600 hover:bg-blue-700 text-white'}`}
            style={variant === "primary" ? { backgroundColor: THEME.TOSCA } : {}}
          >
            {isLoading ? <Loader2 className="animate-spin h-4 w-4" /> : actionLabel}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}